### ISSUE TITLE
feature request: other speed settings possible?

### ISSUE THREAD

**Issue by Finch666** [WrdVdb/BafangSpeedAdjust#1]
Great work this! Program loaded and ready to run as soon as the cables arrive from China :)
Feature request: hex codes for other speed settings. Could not find these anywhere on the web :(

**Comment by WrdVdb** [comment]
You can easily calculate any speed.

AC 0D => 0DAC => 3500 => 35km/h

So if you want 32 => 3200 =>  0C80 in hex => send 85103203 6 80 0C C0 2B CE 08

Someone on Facebook made a list

![FB_IMG_1663876917681](https://user-images.githubusercontent.com/36230484/191840200-531b3479-3853-4a77-9064-7b0b7781a6c6.jpg)

**Comment by WrdVdb** [comment]
Please make sure you read the output first because the other values are tire diameter and such, you want to keep yhem the same.

**Comment by Finch666** [comment]
Awesome! Thanks!
