### ISSUE TITLE
Veloretti Ace: completely different readout

### ISSUE THREAD

**Issue by Barloew** [WrdVdb/BafangSpeedAdjust#2]
Hi Ward, great project - thanks for making it available. I have a recently purchased Veloretti Ace with Bafang engine, like you do. I setup according to you instructions. Unfortunately the output in the serial monitor shows completely different ID's and values in my case. Like this:

```
Setup ok

------ WRITING SPEED ------
------ WRITING SPEED ------
------ WRITING SPEED ------
------ WRITING SPEED ------
------ WRITING SPEED ------
------ WRITING SPEED ------
----------- DONE ----------
----------- DONE ----------
----------- DONE ----------
----------- DONE ----------
----------- DONE ----------
----------- DONE ----------
84F83401 5 0 0 D5 F 3C 
84F81401 1 0 
84F83400 7 D2 33 4 2F 5B 5B 64 
84F83401 5 0 0 D5 F 3C 
84F81400 1 0 
84F83402 1 0 
84F83401 5 0 0 D5 F 3C 
84F83400 7 D2 33 4 2F 5B 5B 64 
84F83401 5 0 0 D5 F 3C 
84F83401 5 0 0 D5 F 3C 
84F83400 7 D2 33 4 2F 5B 5B 64 
84F83401 5 0 0 D5 F 3C 
84F81401 1 0 
84F83401 5 0 0 D5 F 3C 
```
My Ace is on the most recent firmware. Unforttunately, this has meant that the speed hack does not work in my case. Can you offer any suggestion perhaps?

**Comment by WrdVdb** [comment]
That is not a lot of data. Is your bike on when writing? Between setup ok and writing, there should be hundreds of lines.

**Comment by barloew** [comment]
You're right! Beginner's mistake. Bike was turned off due to inactivity. I was successful at the next attempt. Thanks for your project and help.
