### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Birrel01** [WrdVdb/BafangSpeedAdjust#3]
Hello Ward,

Thank you for your great work. I have build the hardware, but have some questions about the software:

What do you mean with: Copy code demo in ino file (try reading without writing the speed setting check if read code starts with 82F83203, first characters could be different)?

Further on I am trying to understand your code and I think that I have to comment out rule 21,22,and 23. Is this true?

This questions are maybe a little stuped, but it is a very long time ago for me working with Arduino.

Kind regards,

Frank.

**Comment by Birrel01** [comment]
Hello Ward,

I think to know how it's works, line 27 and 28 sets the speed? 

Kind regards,

Frank.

**Comment by rickvnl** [comment]
1. Write this ino file to your arduino without editing the file.
2. Connect to your bike and read out
3. If readings are okay set line 9 to true. Write it to your arduino.
4. Connect again and it will adjust the speed.

By the way, I had to recalibrate the bike with  the Enviolo app after adjusting the speed.

**Comment by WrdVdb** [comment]
Line 61 is the line that writes the speed. Comment this line to test the codes you are getting from the bike.

**Comment by Birrel01** [comment]
Thanks for your quick answer, i have compiled and load your file to the Arduino, I connect to the motor, and then? How do I only read the settings without writing. Where must I put the new speed value (i understand the HEX conversion)?

**Comment by Birrel01** [comment]
Sorry, I was not reading very well, so I comment line 61to read the values of the bike, but where to put the new value?

**Comment by WrdVdb** [comment]
Your arduino needs to be connected to a laptop, open the serial monitor in the arduino ide. Set the correct baudrate as specified in the code. Then you will see the data from the bike.

**Comment by Birrel01** [comment]
Oke, I understand this, but in which line do I put the new value?

**Comment by WrdVdb** [comment]
What value have you read? What speed do you want?

This explains it:

```
//Original read: 82F83203 6 C4 09 C0 2B CE 08 => C4 09 => 09C4 => 2500 => 25km/h
  //Set:           85103203 6 AC 0D C0 2B CE 08 => AC 0D => 0DAC => 3500 => 35km/h
  //New read:      82F83203 6 AC 0D C0 2B CE 08
  
  canMsg35.can_id  = 0x85103203 | CAN_EFF_FLAG;
  canMsg35.can_dlc = 6;
  canMsg35.data[0] = 0xAC;
  canMsg35.data[1] = 0x0D;
  canMsg35.data[2] = 0xC0;
  canMsg35.data[3] = 0x2B;
  canMsg35.data[4] = 0xCE;
  canMsg35.data[5] = 0x08;
```
This is the speed bit:

```
canMsg35.data[0] = 0xAC;
  canMsg35.data[1] = 0x0D;
```

**Comment by Birrel01** [comment]
Thank you for your patience, so I read out the motor and will set those  2 bits according the speed I like. (and then wrtite).

According an other message 32 km/h will then be data bit 0: 0x80   and data bit 1:  0x0C
(85103203 6 80 0C C0 2B CE 08)

**Comment by fransjvos** [comment]
Hello Ward,
Thanks for your great project. Almost all seems clear to me and the parts are coming in (but it will take some time unfortunately) ...
While studying the code, I was wondering:
In the ino-file you say check whether the read code starts with 82F8xxxx but in your ino-file you write code starting 8510xxxx. Is there an offset between read code and set code, or do I set the same code as I read from my CAN-bus? 
Thanks,
Frans

**Comment by robertvanson** [comment]
Works like a charm, I used this on an Ace and an Ivy. I commented line 61 first to just get a reading of the current values. Good thing, because one of them differed from the provided example code (canMsg35.data[4] needs to be set to 0xC4 instead of 0xCE for both the bikes I worked on). Finding the value you are looking for in the serial monitor is a bit of a hassle since the bike spits out a lot of values. Thanx for sharing, Ward!

Ps Frans, I don't know why the set and read value differ, but it works.

**Comment by fransjvos** [comment]
Thanks Robert, the last two bytes of msg35 correspond to the circumference of the wheel. Probably you can tune the speedometer a bit?
However the difference between C4 and CE will only be a minor (+/- 10mm).
I did receive all my parts, built it and now enjoy the extra speed and better response around 25kmh 😃 Great project!

**Comment by jpverhoeven** [comment]
Hi, thanks for sharing. Is it possible to write a diffrenet speed than 35? I’ve seen another device (velohacky) which i presume is pretty much the same thing that writes up to 45km/h into the controller If i change the value in lie 61 would this be possible?

**Comment by WrdVdb** [comment]
Yes, check the first messages in this thread. It explains how to write a different hex value for other speeds.

**Comment by dekleik** [comment]
I need help i think….
Build the arduino,installed the IDE,included the library and made the INO file… i can upload the file to my chinese clone,but after that I’am clueless….opening the terminal gives me tons of lines,and connecting the cable to the bike and turn it on.. the same almost empty lines… also the bike does not exceed the 24 km line… arduino in laptop,cable into bike,powering up bike,wait 30 seconds,power off bike,disconnect cable…. Nothing happend

kind regards Mark

**Comment by dekleik** [comment]
![D2C3EC9D-0A89-4091-99B4-7295564B0CE4](https://github.com/WrdVdb/BafangSpeedAdjust/assets/133511896/198d7430-8a84-4342-af57-dd1522028603)

**Comment by fransjvos** [comment]
> I need help i think…. Build the arduino,installed the IDE,included the library and made the INO file… i can upload the file to my chinese clone,but after that I’am clueless….opening the terminal gives me tons of lines,and connecting the cable to the bike and turn it on.. the same almost empty lines… also the bike does not exceed the 24 km line… arduino in laptop,cable into bike,powering up bike,wait 30 seconds,power off bike,disconnect cable…. Nothing happend
> 
> kind regards Mark

Probably you do the wrong order... When you connect the Arduino tot the power / pc, the timer of 10 seconds start.
You should power the bike, then connect the cable with the purple plug and then the USB to power / pc. 
However the output should look something like this:

Setup ok

84F83401 5 0 0 D5 F 3C 
84F81401 1 0 
84F83400 7 D2 33 4 2F 5B 5B 64 
84F83401 5 0 0 D5 F 3C 
84F81400 1 0 
84F83402 1 0 
84F83401 5 0 0 D5 F 3C 
84F83400 7 D2 33 4 2F 5B 5B 64 
84F83401 5 0 0 D5 F 3C 
84F83401 5 0 0 D5 F 3C 
84F83400 7 D2 33 4 2F 5B 5B 64 
------ WRITING SPEED ------
------ WRITING SPEED ------
------ WRITING SPEED ------
------ WRITING SPEED ------
------ WRITING SPEED ------
------ WRITING SPEED ------
----------- DONE ----------
----------- DONE ----------
----------- DONE ----------
----------- DONE ----------
----------- DONE ----------
----------- DONE ----------

So please check if you used the correct module. I have used Atmel atmega328p Xplained... and check your wiring again.
Best of luck!

**Comment by dekleik** [comment]
Thanx!! Will try asap and report,if i choose a different board i cannot upload,could only upload with these specs….
![429FAB8E-36C0-4B22-83F0-F41C562F4323](https://github.com/WrdVdb/BafangSpeedAdjust/assets/133511896/6f5d8259-703b-4eef-95c0-d442c2654858)

**Comment by fransjvos** [comment]
![image](https://github.com/WrdVdb/BafangSpeedAdjust/assets/120576136/2a9e4c99-b7fc-437d-a343-47f70fde01ec)
I use the board in this setting... And COM3 instead of COM5!
![2022-12-23 14 28 06](https://github.com/WrdVdb/BafangSpeedAdjust/assets/120576136/9b5816b6-a6ea-48fa-be41-67f711092809)

**Comment by dekleik** [comment]
No luck with new try…. Com 5 or 6 is what my laptop says in devicemanager.. changing the board(your choise i cannot see in my list) gives an upload error.. so i think i uploaded the sketch…but cannot write to bike… frustrating:)

**Comment by fransjvos** [comment]
You use Arduino 1.8, mine is Arduino IDE 2.1
Maybe upgrade the software?

**Comment by Finch666** [comment]
@dekleik: program seems to have been succesfully uploaded to the arduino. Program seems to run okay, looking at the serial output. Did you make the right connections to the bike? (RX, TX and ground?)

**Comment by dekleik** [comment]
Hmmm,i connected the cable as showed here in topic,only green (high) and white…. And checked several times if the cables are solid into the connection of the canbus

**Comment by Finch666** [comment]
There's little mention of it, but if you don't connect the GND between bike and arduino, no values can be read here; they're just floating around :)
See also: https://togglebit.net/2021/07/22/how-to-properly-wire-a-can-bus/

**Comment by dekleik** [comment]
Hmmmm,if it works for the rest here,do not think my ground is the issue… perhaps my cable isn’t ok…. Will shorten it and try again… have no clue why it isn’t working for me

**Comment by Finch666** [comment]
Another option is to put the jumper on the canbus module (termination). BTW: I use (most of) the original cable length without any issue.

**Comment by dekleik** [comment]
Perhaps can someone confirm that they have the same output in de terminal without the cable connected to the bike… if so,then i know i did correctly upload the sketch.. so i can eliminate that problem;)

i just did order the same stuff as the rest here(followed the links to aliexpress)

**Comment by Finch666** [comment]
Your program is working. Without the cable attached I get no reading whatsoever (arduino keeps waiting for some signal). Your readings show it's working, but you get unreadable output. You really should use the terminator jumper, and quite sure a ground connection to the bike.(https://github.com/autowp/arduino-mcp2515)
https://community.nxp.com/t5/8-bit-Microcontrollers/CAN-bus-To-ground-or-not-to-ground/m-p/187339#:~:text=Not%20only%20is%20it%20necessary,required%20by%20the%20CAN%20standard.

You shouldn't doubt whether the arduino is okay. It is.

**Comment by dekleik** [comment]
Problem solved,my CANmodule was broken,orderd a new one and now it worked!
Thanx for the help!!!

**Comment by SteffanPB** [comment]
canMsg35.data[0] = 0xAC;
canMsg35.data[1] = 0x0D;

What would the values for the above be if I want 45km/h or 65km/h?

**Comment by robertvanson** [comment]
I'd say:

45 km/h:
canMsg35.data[0] = 0x94;
canMsg35.data[1] = 0x11;

65 km/h:
canMsg35.data[0] = 0x64;
canMsg35.data[1] = 0x19;

**Comment by SteffanPB** [comment]
@robertvanson can you elaborate on how you got this? I'd like to learn. 😄

**Comment by robertvanson** [comment]
Sure. Use an online tool to convert Decimal to Hexadecimal like https://www.rapidtables.com/convert/number/decimal-to-hex.html. Enter the desired speed in decimal multiplied bij 100 (so 25 is entered as 2500). The tool will return the hexadecimal value. Make sure the value is a 4 digit string, add a leading 0 in case the value is 3 digits. (the link I provided will do that for you in the "Hex signed 2's complement (4 digits)" box), so 25 km/h is 09C4 in Hex. Split the outcome in two 2 digit values and assign they second value to "canMsg35.data[0]" and the first to canMsg35.data[1]. Don't know why the are inverted in the order.... My learning approach was trail and error, never bothered to find out why :)
