### ISSUE TITLE
Brake cable pinout

### ISSUE THREAD

**Issue by mrshoekstra** [WrdVdb/BafangSpeedAdjust#5]
Hey Ward,

Do you have a pinout of the purple brake cable? I can't find it anywhere and I would like to power the Arduino over the cable.
I probably need a power converter.

**Comment by WrdVdb** [comment]
I think the connection has an 5v pin. 

I have found info on this project: 
https://github.com/OpenSourceEBike/Bafang_M500_M600

But I can't find exactly where at the moment.

**Comment by renownedwolf** [comment]
![Bafang_M500_M600_Brakes_Cable](https://user-images.githubusercontent.com/33104315/231543459-bd450384-69c8-41fb-a14d-d92d5148752a.png)

**Comment by renownedwolf** [comment]
> Hey Ward,
> 
> Do you have a pinout of the purple brake cable? I can't find it anywhere and I would like to power the Arduino over the cable. I probably need a power converter.
![Bafang_M500_M600_Brakes_Cable](https://user-images.githubusercontent.com/33104315/231543588-085f1e74-21e0-4ea2-8e89-cd011409afcd.png)

**Comment by renownedwolf** [comment]
![Bafang_M500_M600_Brakes_Cable](https://user-images.githubusercontent.com/33104315/231543680-44a25d91-62e1-43de-9fa4-1335a333519d.png)
