### ISSUE TITLE
Other BAFANG bicycles?

### ISSUE THREAD

**Issue by Verius83** [WrdVdb/BafangSpeedAdjust#6]
Hi Wart,

Great work! Is this just for veloretti bikes or also other bikes with a BAFANG engine?

Thanks!

**Comment by Radiator99** [comment]
I was wondering the same thing! Anyone?

**Comment by Radiator99** [comment]
Anyone?

**Comment by SteffanPB** [comment]
I tried on a QWIC bike with the same Bafang m200 motor, and I couldn't get output
